Feat js basics
taniaHillel/aqa-advanced-1 pull request #2
Opened 2023-09-03 13:05 UTC by TaniaBystrova

js basics homework

2023-09-03 13:21 UTC, sttaran requested changes

2023-09-03 13:21 UTC, sttaran commented on git_basics/gitignore
`.gitignore `file should be placed on the root of the project. 
Path for each entry should be relative
e.g.
`/js_basics//node_modules`

2023-09-03 13:21 UTC, sttaran commented on git_basics/readme.md
you should create new branch based on main branch if another condition is not specified

2023-09-03 13:21 UTC, sttaran commented on js_basics/node_modules/.package-lock.json
node_modules should be ignored by git

2023-09-03 13:21 UTC, sttaran commented on js_basics/task4.js
> +const isAdult = age > 18
`const isAdult = age >= 18`

2023-09-03 13:21 UTC, sttaran commented on js_basics/task4.js
> +let age = 21
use const instead of let

2023-09-03 13:21 UTC, sttaran commented on js_basics/task3.js
> +let name2 = 'Ann'
use const instead of let

2023-09-03 13:21 UTC, sttaran commented on js_basics/task5_1.js
> +let radius  = 12
use const instead of let

2023-09-03 13:21 UTC, sttaran commented on js_basics/task5_2.js
> +let length = 10.53
use const instead of let

2023-09-03 13:21 UTC, sttaran commented on js_basics/task5_3.js
> +let height = 15
use const instead of let

2023-09-03 13:21 UTC, sttaran commented on yarn.lock
this file should be excluded, It has no relation to task

2023-09-03 15:40 UTC, closed without merging

2023-09-04 07:23 UTC, TaniaBystrova commented on yarn.lock
I have deleted this file, what was expected?